// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOn08iq5noNUJcNe6f9Fzorekaje0tg8k',
    appId: '1:485956070582:android:d5d2c464ee844fc0a9ca17',
    messagingSenderId: '485956070582',
    projectId: 'chat-app-9f011',
    storageBucket: 'chat-app-9f011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkANdQDdIN7gZIHCdn_9O0a0g_ZR5Relc',
    appId: '1:485956070582:ios:0b93a5c4d5c83affa9ca17',
    messagingSenderId: '485956070582',
    projectId: 'chat-app-9f011',
    storageBucket: 'chat-app-9f011.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkANdQDdIN7gZIHCdn_9O0a0g_ZR5Relc',
    appId: '1:485956070582:ios:0b93a5c4d5c83affa9ca17',
    messagingSenderId: '485956070582',
    projectId: 'chat-app-9f011',
    storageBucket: 'chat-app-9f011.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
